CREATE TABLE LOG_HANH_VI (
    MaLog VARCHAR2(50) PRIMARY KEY,
    LoaiHanhDong VARCHAR2(50), -- 'XEM_SK'|'CLICK_DAT_VE'|'BO_GIO_HANG'
    MaSK VARCHAR2(50),
    ThoiGian TIMESTAMP DEFAULT SYSTIMESTAMP,
    MaKH VARCHAR2(50),
    ThietBi VARCHAR2(20) -- 'Web'|'Mobile'
);
/
