-- 1. Nhóm Sự kiện & Địa điểm
ALTER TABLE SUKIEN ADD CONSTRAINT FK_SK_LOAISK
    FOREIGN KEY (MaLoaiSK) REFERENCES LOAISUKIEN(MaLoaiSK);

ALTER TABLE SUKIEN ADD CONSTRAINT FK_SK_DIADIEM
    FOREIGN KEY (MaDiaDiem) REFERENCES DIADIEM(MaDiaDiem);

ALTER TABLE SUKIEN ADD CONSTRAINT FK_SK_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE KHUVUC ADD CONSTRAINT FK_KV_SUKIEN
    FOREIGN KEY (MaSK) REFERENCES SUKIEN(MaSK);

ALTER TABLE GHENGOI ADD CONSTRAINT FK_GHE_KHUVUC
    FOREIGN KEY (MaKhuVuc) REFERENCES KHUVUC(MaKhuVuc);

ALTER TABLE GHENGOI ADD CONSTRAINT FK_GHE_SUKIEN
    FOREIGN KEY (MaSK) REFERENCES SUKIEN(MaSK);

-- 2. Nhóm Người dùng & Khách hàng
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KH_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KH_HANGTHANHVIEN
    FOREIGN KEY (MaHangThanhVien) REFERENCES HANGTHANHVIEN(MaHangThanhVien);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_QUANLY
    FOREIGN KEY (MaNQL) REFERENCES NHANVIEN(MaNV);

-- 3. Nhóm Phân quyền (RBAC - tái sử dụng từ workspace gốc)
ALTER TABLE CHITIETVAITRO ADD CONSTRAINT FK_CTVT_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE CHITIETVAITRO ADD CONSTRAINT FK_CTVT_VAITRO
    FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro);

ALTER TABLE CHITIETNHOMCHUCNANG ADD CONSTRAINT FK_CTNCN_VAITRO
    FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro);

ALTER TABLE CHITIETNHOMCHUCNANG ADD CONSTRAINT FK_CTNCN_NHOMCN
    FOREIGN KEY (MaNhomChucNang) REFERENCES NHOMCHUCNANG(MaNhomChucNang);

ALTER TABLE CHITIETCHUCNANG ADD CONSTRAINT FK_CTCN_NHOMCN
    FOREIGN KEY (MaNhomChucNang) REFERENCES NHOMCHUCNANG(MaNhomChucNang);

ALTER TABLE CHITIETCHUCNANG ADD CONSTRAINT FK_CTCN_CHUCNANG
    FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang);

-- 4. Nhóm Bán vé & Thanh toán
ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_PHIEUGIAMGIA
    FOREIGN KEY (MaPGG) REFERENCES PHIEUGIAMGIA(MaPGG);

ALTER TABLE DONHANG ADD CONSTRAINT FK_DH_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE VE ADD CONSTRAINT FK_VE_DONHANG
    FOREIGN KEY (MaDonHang) REFERENCES DONHANG(MaDonHang);

ALTER TABLE VE ADD CONSTRAINT FK_VE_GHENGOI
    FOREIGN KEY (MaGhe) REFERENCES GHENGOI(MaGhe);

ALTER TABLE VE ADD CONSTRAINT FK_VE_SUKIEN
    FOREIGN KEY (MaSK) REFERENCES SUKIEN(MaSK);

ALTER TABLE GIAODICHTHANHTOAN ADD CONSTRAINT FK_GD_DONHANG
    FOREIGN KEY (MaDonHang) REFERENCES DONHANG(MaDonHang);

ALTER TABLE PHIEUGIAMGIA ADD CONSTRAINT FK_PGG_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

-- 5. Nhóm Kiểm soát & Hàng đợi
ALTER TABLE LICHSUSOATVE ADD CONSTRAINT FK_LSSV_VE
    FOREIGN KEY (MaVe) REFERENCES VE(MaVe);

ALTER TABLE LICHSUSOATVE ADD CONSTRAINT FK_LSSV_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE HANGDOIAO ADD CONSTRAINT FK_HDT_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE HANGDOIAO ADD CONSTRAINT FK_HDT_SUKIEN
    FOREIGN KEY (MaSK) REFERENCES SUKIEN(MaSK);

ALTER TABLE NHATKYQUYENHANTRO ADD CONSTRAINT FK_NK_THUCHIEN
    FOREIGN KEY (MaND_ThucHien) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE NHATKYQUYENHANTRO ADD CONSTRAINT FK_NK_BITHAYĐOI
    FOREIGN KEY (MaND_BiThayDoi) REFERENCES NGUOIDUNG(MaND);
