CREATE INDEX IDX_VE_MAQR ON VE(MaQR);
CREATE INDEX IDX_GHE_SK_TRANGTHAI ON GHENGOI(MaSK, TrangThaiGhe);
CREATE INDEX IDX_HANGDOIAO_SK ON HANGDOIAO(MaSK, TrangThai);
CREATE INDEX IDX_DONHANG_KH ON DONHANG(MaKH, TrangThaiDonHang);
CREATE INDEX IDX_LSSV_VE ON LICHSUSOATVE(MaVe, DaDongBo);
/
