# Cấu hình Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=123456

# Cấu hình Hibernate cho Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cổng chạy ứng dụng
server.port=8081

# Log bảo mật
logging.level.org.springframework.security=INFO
