CREATE TABLE MembershipTiers (
    tier_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_name        VARCHAR2(50) NOT NULL UNIQUE,  -- BRONZE, SILVER, GOLD, DIAMOND
    min_points       NUMBER DEFAULT 0 NOT NULL,
    discount_percent NUMBER(5, 2) DEFAULT 0,         -- % giảm giá khi mua vé
    description      VARCHAR2(255),

    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
