CREATE TABLE Functions (
    function_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    function_code VARCHAR2(50) UNIQUE NOT NULL,  -- VD: FUNC_EVENT_MANAGE, FUNC_TICKET_SCAN
    function_name VARCHAR2(100) NOT NULL,         -- Tên hiển thị
    module_name   VARCHAR2(50),                   -- Gom nhóm: EVENT, TICKET, PAYMENT, REPORT

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted    NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0, 1))
);
