CREATE TABLE Permissions (
    permission_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    function_id   NUMBER(10) NOT NULL,  -- Thuộc chức năng nào (FK -> Functions)

    -- Ma trận phân quyền (1: Có quyền, 0: Không)
    can_view      NUMBER(1) DEFAULT 0 CHECK (can_view IN (0, 1)),
    can_add       NUMBER(1) DEFAULT 0 CHECK (can_add IN (0, 1)),
    can_edit      NUMBER(1) DEFAULT 0 CHECK (can_edit IN (0, 1)),
    can_delete    NUMBER(1) DEFAULT 0 CHECK (can_delete IN (0, 1)),

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted    NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0, 1))
);
