CREATE TABLE Roles (
    role_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name      VARCHAR2(100) NOT NULL UNIQUE,
    description    VARCHAR2(255),
    is_system_role NUMBER(1) DEFAULT 0 CHECK (is_system_role IN (0, 1)),

    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active      NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    is_deleted     NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0, 1))
);
